### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by martindevans** [martindevans/SupersonicSound#1]
I have no idea how to release a nuget package with native dependencies, investigate this and then release a nuget package.

**Comment by martindevans** [comment]
I forgot that I've done this before! [See here](https://github.com/martindevans/RecastManaged) for how to do it (private repo)

**Comment by martindevans** [comment]
[Done](https://www.nuget.org/packages/SupersonicSound/)!

**Comment by HakanL** [comment]
You should create a tag in Git that corresponds with the NuGet release so it's easy to know what's released

**Comment by martindevans** [comment]
Good idea. I'll do that for future releases :)

**Comment by HakanL** [comment]
If you know when you created the nuget package then you can create the tag to that git commit in the history and push it to github.

**Comment by martindevans** [comment]
I'm afraid I'm not certain which version is the current one :(

**Comment by HakanL** [comment]
Ah, no worries, maybe just release a new one soon ;)
