### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by martindevans** [martindevans/SupersonicSound#16]
@HakanL We have release [3.0.0 on nuget](https://www.nuget.org/packages/SupersonicSound/3.0.0) and this time it's [tagged](https://github.com/martindevans/SupersonicSound/tags) as per your suggestion.

Thanks for all your hard work to get this release out :D

**Comment by HakanL** [comment]
Awesome! My pleasure! Now I can play sounds on my RPis for my Halloween display! ;) :+1:
