### ISSUE TITLE
ChannelControl is not exposed

### ISSUE THREAD

**Issue by martindevans** [martindevans/SupersonicSound#17]
Investigate the usage of [ChannelControl](https://github.com/martindevans/SupersonicSound/blob/03dbda99f92128581a42cf4c58841c709717ac8b/SupersonicSound/Wrapper/Fmod/fmod.cs#L2843) and expose it appropriately in SSS

**Comment by martindevans** [comment]
D'oh! Channel extends ChannelControl. There may be some channel control functionality not exposed on the channel struct (specifically interested in callbacks), implement this.

**Comment by martindevans** [comment]
Also check channel group, probably needs all the same methods implemented

**Comment by martindevans** [comment]
Added [IChannelControl](https://github.com/martindevans/SupersonicSound/blob/master/SupersonicSound/LowLevel/IChannelControl.cs) which has the same signature as FMOD.ChannelControl. Added the interface to necessary structs (Channel and ChannelGroup).

Missing functionality is currently commented out within this interface

**Comment by HakanL** [comment]
Please see if this commit makes sense instead: https://github.com/HakanL/SupersonicSound/commit/a5fedb3d654dd5faf6e578780de66475f03d96a9

**Comment by martindevans** [comment]
Yep this looks pretty good - want to put that into a PR?

I didn't make myself clear with the whole IChannelControl stuff - in FMOD ChannelControl is the _base class_ of Channel and ChannelGroup. ChannelControl is where setCallback is defined, so your commit is basically implementing part of the IChannelControl interface for me.

**Comment by HakanL** [comment]
Ah ok got it. I'll do a little more work on the callback before I do a PR, not too happy with keeping a list of callbacks, I'll try something else.

**Comment by martindevans** [comment]
Yeah I wanted you to submit a PR of just the first bit, without the list of callbacks. I want to experiment with alternatives to keeping a list because I don't like that either.

**Comment by martindevans** [comment]
This issue is resolved now, we got a little off track discussing it - we should move back over to [here](https://github.com/martindevans/SupersonicSound/issues/18)
