### ISSUE TITLE
Create event sample

### ISSUE THREAD

**Issue by HakanL** [martindevans/SupersonicSound#18]
Sample that raises an event when a channel has finished playing a sound.

**Comment by HakanL** [comment]
@martindevans please take a look at this commit if this makes sense to add to SSS for callbacks. If ok then I can add the code to ChannelGroup as well. I still don't think the IChannelGroup interface do much for us, but of course it doesn't harm either.

**Comment by HakanL** [comment]
I just realized that an issue with this code is when the channel is disposed the callback will fail, turns out there isn't a way to unset a callback via the FMOD api. I'm testing out a couple of different ways, but if you have any suggestions feel free to give me feedback.

**Comment by martindevans** [comment]
Have you tested that your [first commit above](https://github.com/HakanL/SupersonicSound/commit/a5fedb3d654dd5faf6e578780de66475f03d96a9) fails when the channel is disposed? I would assume that the callback becomes implicitly unregistered by FMOD when FMOD cleans up the channel handle.

Could you put the first commit into a PR for now? I'd like to have a fiddle with it.

**Comment by martindevans** [comment]
There was some discussion of this issue in [this other issue](https://github.com/martindevans/SupersonicSound/issues/17)

**Comment by HakanL** [comment]
Sorry about the delay, had to call it an early night. I'll look into this tomorrow. You should be able to see the commit in my fork without a PR though.

**Comment by martindevans** [comment]
Ok I pulled in your commit, and verified that it does fail if the delegate gets garbage collected.

**Comment by martindevans** [comment]
I had a bit more of a fiddle with this. I could only think of two solutions:
- Store the callbacks in the channel struct. This isn't great because it means the user has to keep the channel struct around somewhere until it is finished with (and that's still risky, if they drop it too soon we get an exception when an event happens some random time later).
- Store the callbacks in a list in the system. When update is called on the system we check all registered callbacks to see if the handle is valid (how?) and then delete the ones which are finished with.

**Comment by HakanL** [comment]
I think I've found a solution to this. .NET has a function in the GC called GCHandle which is used to keep the GC from disposing delegates. The issue is that it has to be freed at some point or it will leak. So I'm storing the handle in the Channel object and when the callback with type END is called that's when I release the handle (because after END callback the channel is done). I also added a way to remove a callback, I tested out SetCallback in FMOD by calling it with NULL and it stopped calling my callback, so 1) it only supports one callback, and 2) setting it to null will remove the callback. Not sure if RemoveCallback is really needed, but I thought it was a nice feature to have available.

You can test out the disposing of the delegate in SetCallback by commenting out this line in Channel and running the ChannelCallback sample:

>    _callbackHandle = GCHandle.Alloc(callbackFunction);

It should then give you the dispose callback exception.

**Comment by HakanL** [comment]
I did a PR for this issue btw, I think that may close this issue. I also added it to ChannelGroup.

**Comment by martindevans** [comment]
Closing this as we have a sample for raising an event when a sound stops
