### ISSUE TITLE
Upgrade to FMOD 1.06

### ISSUE THREAD

**Issue by HakanL** [martindevans/SupersonicSound#2]

**Comment by martindevans** [comment]
Have you already started on this work? Someone else contacted me about doing this a while back, but I don't know what progress they made.

**Comment by HakanL** [comment]
I started, but then I realized I should make it work on Mono first, so I rolled back my changes. I may still do it, we'll see what time I can find :)

**Comment by martindevans** [comment]
Give me another ping on this issue when you're about to start an upgrade to 1.06 and I'll tell you if someone else has already started :)

**Comment by HakanL** [comment]
Sure!

**Comment by HakanL** [comment]
Ok, I started, and finished :)

**Comment by HakanL** [comment]
I have a PR ready for FMOD 1.06, but since it's based on the changed I did in the first pull request I'll submit it to you when you've merged the first PR so it can be based on that.

**Comment by HakanL** [comment]
Even worked on the Raspberry Pi! This has been a good day :)

**Comment by martindevans** [comment]
Wow ok that was a pretty quick upgrade! I await it eagerly :D

**Comment by HakanL** [comment]
PR submitted

**Comment by martindevans** [comment]
PR merged
