### ISSUE TITLE
Low Level Validity Checking

### ISSUE THREAD

**Issue by martindevans** [martindevans/SupersonicSound#22]
Low level types can become invalid at any time, the only way to check is to check the return result of calls to see if it is FMOD_ERR_INVALID_HANDLE or FMOD_ERR_CHANNEL_STOLEN. This is problematic in SSS because these become _exceptions_ which makes handling this case extremely ugly (all calling code must be wrapped in a try block with a handler for these exceptions).

Discussion in [this thread](https://github.com/martindevans/SupersonicSound/issues/19) eventually settled on a solution for this problem:
- By default suppress these two errors, have two per struct flags to toggle suppression.
  - SuppressInvalidHandle
  - SuppressChannelStolen
- In setters there is no additional special handling; either the error is ignored entirely or an exception is thrown (depending on the flag values)
- In getters return nullable values; and also throw if the flags require it

**Comment by martindevans** [comment]
Structs which this change will affect:
- [x] Channel~
- [x] ChannelGroup~
- [x] DSP
- [x] DSPConnection
- [ ] Geometry
- [x] Reverb3D
- [x] Sound
- [x] SoundGroup
- [ ] System

~These systems have the additional _channel_stolen_ flag.

**Comment by martindevans** [comment]
I'm going to have a crack at implementing (at least partly) this on Channel right now. Just as an example of how I think this should be done.

**Comment by martindevans** [comment]
Implemented this for two methods in Channel (in a branch right now, see [here](https://github.com/martindevans/SupersonicSound/blob/feature/lowlevelerrors/SupersonicSound/LowLevel/Channel.cs#L63)). This was mostly writing a set of helper functions to make doing this easy, most of the remaining work will just be mechanical substitution.

**Comment by martindevans** [comment]
Implemented this for all of Channel and ChannelGroup, updated callback example to remove the try/catch

**Comment by HakanL** [comment]
:+1:  I gotta check it out!

**Comment by martindevans** [comment]
This pattern ends up leaving some method calls rather ugly. e.g.

```
public void GetChannelFormat(out ChannelMask? channelMask, out int? numChannels, out SpeakerMode? sourceSpeakerMode)
```

If you call this you end up with _three_ nullables, which are either all Some or all None. Once the basic conversion to this pattern is complete we could consider a further enhancement to fix this:

```
public ChannelFormatResult? GetChannelFormat()
```

This way there is only one nullable (effectively a tuple of the results).

**Comment by HakanL** [comment]
I like that approach with returning a ChannelFormatResult.

**Comment by martindevans** [comment]
Result struct work list:
- [x] Channel~
- [x] ChannelGroup~
- [x] DSP
- [x] DSPConnection
- [ ] Geometry
- [x] Reverb3D
- [x] Sound
- [x] SoundGroup
- [ ] System

~These systems have the additional _channel_stolen_ flag.

I've implemented the new result struct system for _Sound_, I'll probably go back and implement it for _Channel_ and _ChannelGroup_ next as I guess these are the three structs you're using most. Once that's done I'd appreciate any feedback you have on the ergonomics of the new system :)

**Comment by HakanL** [comment]
In my application I actually only use the GetPosition on the channel and that worked really well with these changes.

**Comment by martindevans** [comment]
I've applied this pattern to all types except Geometry and System (LowLevel or Studio). I don't see how a handle going null for any of these is anything but an error!

Going to close this issue now
