### ISSUE TITLE
Upgrade to FMod 1.07

### ISSUE THREAD

**Issue by HakanL** [martindevans/SupersonicSound#24]

**Comment by HakanL** [comment]
Outstanding issue is to see why setSubSound was removed from FMOD's C# wrapper. I have an email into them about that. I commented it out at the moment and throw an exception (https://github.com/HakanL/SupersonicSound/commit/061f7f7507023c644792669ba6d9a022771a726d#diff-dd6f81603b2ea66e2d57e20558bbed81L159)

**Comment by HakanL** [comment]
It's still listed in their documentation: http://www.fmod.org/docs/content/generated/FMOD_Sound_SetSubSound.html

**Comment by martindevans** [comment]
Looks like a bug their end, the [patch notes](http://www.fmod.org/files/studio_api_revision.txt) make no mention of subsounds whatsoever.

**Comment by HakanL** [comment]
Here's the response from FMOD:
Sound::setSubSound was indeed removed in 1.07.

The removal should have been mentioned in revision.txt (it appears it wasn't).
It has been unlinked from the navigation tree in the online docs but it seems the page for the API is still there (it should be removed).

The wrapper is correct and reflects the C / C++ API headers.

So I assume it is no longer possible to set a subsound. I'll remove the setter and do a PR if you agree.

**Comment by martindevans** [comment]
Yep, that sounds like a pretty comprehensive response from them. Go ahead and remove it :)

**Comment by HakanL** [comment]
Sounds good. I asked what it was used for and here's the answer for full clarity:

Files like FSB and DLS have multiple subsounds, you can query them via getSubSound.

The concept of building an empty container Sound and using setSubSound isn't useful any longer.
It's a hold over from earlier versions that supported a "subsound sentence", like a play list.
The setSubSound function has been overlooked and should have been removed long ago.

**Comment by HakanL** [comment]
Created PR https://github.com/martindevans/SupersonicSound/pull/27

**Comment by martindevans** [comment]
Merged that PR, closing this.

Duplicating my comment from the PR:

> You've done two of these version upgrades now, do you have any kind of process you follow? If you do I'd appreciate it if you threw together some notes on the process in a wiki page. That'll simplify it a lot for other people to conduct future upgrades.

**Comment by HakanL** [comment]
Certainly: https://github.com/martindevans/SupersonicSound/wiki/FMOD-Upgrade
