### ISSUE TITLE
Support mono/Raspberry Pi

### ISSUE THREAD

**Issue by HakanL** [martindevans/SupersonicSound#4]
Already started that work, but I figured we should have an issue opened for it.

**Comment by martindevans** [comment]
Great :+1:

I think you're probably going to encounter two big challenges here:
- LoadLibrary and FreeLibrary both are imported from kernel32, not at all cross platform!
- The native loader assumes x86 or x64, I'm not sure how you'll distinguish ARM platforms.

**Comment by HakanL** [comment]
That part is already done, with my pull request I can run it on Linux now (but you have to manually add the FMOD libraries to your lib folder, that part isn't automated. Basically you don't need the LoadLibrary/FreeLibrary tracking in Mono, it will load the necessary lib from the DllImport when used.

On Raspberry Pi 1 the arch is armhf, but so far I haven't attempted to dynamically load them, to be honest I'm not too familiar with how that works in Linux, I just copied them to the lib folder per some instructions I found for fmod.

**Comment by martindevans** [comment]
I'm reading over your PR now. I don't have a linux dev environment to test it on unfortunately so I'm just going to have to take your word for it that it works!

**Comment by HakanL** [comment]
I've tested it in Windows as well to make sure I didn't break anything obvious. I did roll a little too much into the commit, but I had to start with a simple PlaySound, so I did the changes to the ConsoleTest and made sure that worked in Windows before I started with Mono. That's when I noticed that the shutdown code threw exceptions so I figured I'd fix that first. That's probably the area you should take a look at, I added an Obsolete attribute on a part that didn't seem to be used and if the Close on the lowlevel system was called then Release failed on the Studio.

**Comment by HakanL** [comment]
What, no RPi? I thought all Brits were given those at birth? ;)

**Comment by martindevans** [comment]
Haha :+1:

I do have an RPi, but I don't have it properly set up as a development environment at the moment.

**Comment by martindevans** [comment]
Merged in that PR. Would you mind typing up a little bit for the readme explaining what needs to be done for linux (pretty much just what files need to be put where). I'll write up the same for windows and then remove SupersonicSound.Dependencies per #8

**Comment by HakanL** [comment]
Cool, thanks! I don't know if this process is the best way in Linux but this is what I did. I can write up the exact steps later.
- Download FMOD for Linux
- Extract tar file
- Copy libfmod.so.X.Y and libfmodstudio.so.X.Y to /usr/local/lib/
- Link libfmod.so to the versioned file, same for libfmodstudio.so
- Run ldconfig

**Comment by martindevans** [comment]
We have another issue for the linux writeup, so I'll close this issue now.
