### ISSUE TITLE
Add note to documentation that .NET 4.6 is required

### ISSUE THREAD

**Issue by HakanL** [martindevans/SupersonicSound#5]
I tried to go to 4.5 but Vector3 isn't available so I assume .NET 4.6 is required (which is fine with me, still works fine in Mono), but we should probably have a note on the first documentation page as it may be an issue for some.

**Comment by martindevans** [comment]
The big change is that .net 4.5 pulls System.Numerics into the framework. I believe you can work around this by installing [System.Numerics.Vectors](https://www.nuget.org/packages/System.Numerics.Vectors/) on lower platforms.

Do you know if it's possible to have platform dependent nuget dependencies?
- [ ] Check using nuget package on a lower platform

**Comment by HakanL** [comment]
That's fine, but it should probably be stated somewhere so potential users know that out of the box it's .NET4.6 (but is possible to work with 4.5), or if you prefer to downgrade the library to 4.5 to make it more accessible and add necessary dependencies.

Not sure how that works, I think it's possible in NuGet, they have net40, etc folders...

**Comment by martindevans** [comment]
I'll add a note to the readme about it's being .net4.6 only for now.
