### ISSUE TITLE
Low Level Initialization

### ISSUE THREAD

**Issue by martindevans** [martindevans/SupersonicSound#7]
The FMOD.Studio.System contains a FMOD.LowLevel.System internally. When the studio system is initialized this automatically initializes the low level system.

The LowLevelSystem property exposed on Studio.System exposes a low level system which a user could, incorrectly, call initialize on. Instead we should expose an interface ILowLevelSystem which contains only the things we want the user to access (probably everything except init and disposal).

**Comment by martindevans** [comment]
I'll probably implement this after merging [this PR](https://github.com/martindevans/SupersonicSound/pull/3)

**Comment by HakanL** [comment]
I implemented it using the same pattern as the Studio.System so there's a constructor to LowLevelSystem that takes channels and init flags and it will then call init, etc. See if that works for this issue.

**Comment by martindevans** [comment]
Merged in the PR, which now resolves this issue
