### ISSUE TITLE
Need to remove FMOD binaries, violates EULA

### ISSUE THREAD

**Issue by HakanL** [martindevans/SupersonicSound#8]
From FMOD:

> I've had a quick look at the GitHub page and I can see the FMOD binaries are checked in.
> This is a violation of our license, could you please remove them?
> 
> We are happy to see developers extending the usefulness of FMOD through an enhanced C# interface, but it is important that the binaries are sourced directly from us including full EULA.
> If you could instead direct people to our downloads page for the dependencies that would be ideal.

**Comment by martindevans** [comment]
Oh no! I did check whether it was ok for me to distribute the binaries, obviously I missed this D:

I'll fix this one as soon as I have merged the PR. Hopefully later tonight.

My one technical concern with this is that users will be downloading the latest version of FMOD, but obviously SSS is not always up to date. Hopefully this won't be a problem though.

**Comment by HakanL** [comment]
If users are just staying within the same API version (1.05, 1.06, etc) then it their minor patches should all be compatible. But obviously it's more work for the users, but with some instructions of just downloading and copying the binaries into the right folder I think it'll be fine.

**Comment by martindevans** [comment]
This is fixed in repo, but not yet pushed up to nuget. I'll push up a new nuget version once the upgrade to 1.06 is complete

**Comment by HakanL** [comment]
I added a bat file to simply copy the binaries from the FMOD Windows installation.

**Comment by HakanL** [comment]
And I created a PR for it, see if it's something you want to add.

**Comment by martindevans** [comment]
merged that
