### ISSUE TITLE
Write up better instructions for how to install SSS/FMOD in Unix

### ISSUE THREAD

**Issue by HakanL** [martindevans/SupersonicSound#9]

**Comment by martindevans** [comment]
I just modified the readme to have [installation instructions](https://github.com/martindevans/SupersonicSound#installation-instructions) (currently windows only).

**Comment by HakanL** [comment]
I'll add the Linux/RPi instructions later and then you can merge that into the readme (or wiki?)

**Comment by martindevans** [comment]
Thanks :)

If the instructions are too long for the readme feel free to write them up in a wiki page and just link them from the readme.

**Comment by HakanL** [comment]
See if this works, I wish there was a simpler way to install these...
https://github.com/martindevans/SupersonicSound/wiki/Linux-FMOD-Studio-Installation

**Comment by martindevans** [comment]
Thanks for this :D

I've modified the readme to point to separate wiki pages for windows and linux installation processes.
